# -*- coding: utf-8 -*-
"""DSAC-FA-MVP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mWM6ffUy55x2okYKn-EDFpu5CD4L99f9
"""

# import yfinance library
import yfinance as yf
import pandas as pd

class stock_data:
  start_date = '2021-01-01' 
  end_date = '2021-12-31'

  # created function to fetch the stock related data from yfinance API
  def fetch_data(self, ticker):
    data = yf.download(ticker, start=self.start_date, end=self.end_date)
    return data

# created instace of class
stock = stock_data()

# collect stock data for Tesla
tesla_data = stock.fetch_data('TSLA')
print("Stock Data of Tesla")
print(tesla_data)

# collect stock data for Ford
ford_data = stock.fetch_data('F')
print("Stock Data of Ford")
print(ford_data)